language: Java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- "./gradlew releaseZip"
deploy:
  provider: heroku
  api_key:
    secure: g0UU9pz95m8e6B/p7UjjEMei4JsXQwmRkO7nnuflVR0i9aLjx3ooRJAhY4HRGj1X7biTD1sD2TFlGDhekGEKOl0tcledZAU61QknG7SR12ic8cXtB1fVr3YFZ9JLFoXV9MoivfaMbkmvcQ099DvVmjoc5C4mj/02Iu8SWUChVwcaCnc89/VU+QX3w0FesyiWl+tFOPrfdfyBTkRzJt9SAIJWnQj19AOm1nRB5GveVkz/rvRKRWkoMGWcJVVSN9Htuk1udST6lvz/Eet7AvWYPVqJJ/uSILagBduwY1ze75sYs4H5JF9cmcFDpgtXH5PqbjTXIq3kv5UdiLa/aCsCI4XgQ3NKM52xpCycpxH4rqB3LnAkBA5mPkcDIibCIF6nyWwHT7ip2sU0O2pWqPUkVnA/lhqTeUJGbAwnNz8zHN0voUZybWRVLdD2bH+K0FQG/IXfnBJVBl7doxVdd7qAkTI3OHmCxkc0n+JrNF9f7VO7C8mByNkaK+vtiErBB3Qw353ckV0R1FY5sfvvv07ImIQS35Ufdp8NOAQODHFsryGKWpiZtkLcMpjeBw1m5Bh2zIJGEYlnoMSSQowu6/3d1yF+pfZ8nnWTy3uEXr+Q32eIcrqB9+YUJd5m51Zp8yvxZKyy/VpNWOs5PVZeFbx1XegVRA1KIpWz1XS/4zVczDY=
  app: bprzybylski-jalgoarena-api
  on:
    repo: bartpr/JAlgoArena-API
